// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYf1Y2C59BNvTSrEfh4tQ5Ghvk3F-k3Do',
    appId: '1:326334951620:web:24b46c2d3f6e358b045991',
    messagingSenderId: '326334951620',
    projectId: 'portfolio-flutter-web-86ff6',
    authDomain: 'portfolio-flutter-web-86ff6.firebaseapp.com',
    storageBucket: 'portfolio-flutter-web-86ff6.appspot.com',
    measurementId: 'G-6KTBDY39M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANn-Q9woaqiTivw5i25x7Wjm0z1OlKJcw',
    appId: '1:326334951620:android:626f96fccf1efbef045991',
    messagingSenderId: '326334951620',
    projectId: 'portfolio-flutter-web-86ff6',
    storageBucket: 'portfolio-flutter-web-86ff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4EiIjOgw_3ncZ0yYVtD82P38FthIbnI',
    appId: '1:326334951620:ios:a08adeb3b87a50e1045991',
    messagingSenderId: '326334951620',
    projectId: 'portfolio-flutter-web-86ff6',
    storageBucket: 'portfolio-flutter-web-86ff6.appspot.com',
    iosClientId: '326334951620-omj8deg6ps86g9faqjqi63vedltufp4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioWeb',
  );
}
